import createHttpError from "http-errors";
import { NextApiRequest, NextApiResponse } from "next";
import transporter from "utils/transporter";

export default async function handler(
  request: NextApiRequest,
  response: NextApiResponse
) {
  const { method } = request

  if(method === "POST"){
    
    try {
      await transporter.sendMail({
        from: 'â˜• <coffee@example.com>', // sender address
        to: "ommv.17@gmail.com", // list of receivers
        subject: "NotificaciÃ³n de Dinner and Coffee â˜•", // Subject line
        html: `
          <div>
            <h2><strong>Leo acaba de ver la APP!!!!</strong></h2>
            <p>ðŸ˜³ðŸ˜³ðŸ˜³ðŸ˜³ðŸ˜³ðŸ˜³ðŸ˜³ðŸ˜³ðŸ˜³ðŸ˜³</p>
          </div>
        `, // html body
      });

      console.log("Sent Notification!")

      response.status(200).json({ message: "NotificaciÃ³n enviada!" })

    } catch (error) {
      console.log(error)
      const { statusCode, message } = new createHttpError.InternalServerError()
      response.status(statusCode).json({
        message: `Ha habido un error con la NotificaciÃ³n!\n ${message}`
      })
    }
    
  }else{
    const { statusCode, message } = new createHttpError.MethodNotAllowed()
    response.status(statusCode).json({ message })
  }
  
}